---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Demo Application</title>
        <link href="styles.css" rel="stylesheet" type="text/css">
      </head>
      <body>
        This is an example KOTS application packaged with Replicated
        <p>Deployed By: '{{repl ConfigOption "name"}}' </p>
        </br>
        <p>Manifests URL: '{{repl ConfigOption "github_url"}}' </p>
      </body>
    </html>
  styles.css: |
    body {
      text-align: center;
      background-color: rgb(224,224,224);
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 200%;
      margin-top: 25%;
    }
